CLASSE_PROBLEMA = 0
CLASSE_AGRADECIMENTO = 1
CLASSE_SAUDACAO = 2
CLASSE_OUTROS = 3
CLASSE_DUVIDA = 4
CLASSE_NEGACAO = 5
CLASSE_CONFIRMACAO = 6
CLASSE_INFORMACAO = 7

LABEL_PROBLEMA = 'PROBLEMA'
LABEL_AGRADECIMENTO = 'AGRADECIMENTO'
LABEL_SAUDACAO = 'SAUDACAO'
LABEL_OUTROS = 'OUTROS'
LABEL_DUVIDA = 'DUVIDA'
LABEL_NEGACAO = 'NEGACAO'
LABEL_CONFIRMACAO = 'CONFIRMACAO'
LABEL_INFORMACAO = 'INFORMACAO'

label_to_text = {
    CLASSE_PROBLEMA: LABEL_PROBLEMA,
    CLASSE_AGRADECIMENTO: LABEL_AGRADECIMENTO,
    CLASSE_SAUDACAO: LABEL_SAUDACAO,
    CLASSE_OUTROS: LABEL_OUTROS,
    CLASSE_DUVIDA: LABEL_DUVIDA,
    CLASSE_NEGACAO: LABEL_NEGACAO,
    CLASSE_CONFIRMACAO: LABEL_CONFIRMACAO,
    CLASSE_INFORMACAO: LABEL_INFORMACAO
}